export const CREATE_BOT = "CREATE_BOT";
export const RETRIEVE_BOTS = "RETRIEVE_BOTS";
export const UPDATE_BOT = "UPDATE_BOT";
export const DELETE_BOT = "DELETE_BOT";
export const BOT_REQUEST = "BOT_REQUEST";
export const BOT_SUCCESS = "BOT_SUCCESS";
export const BOT_FAILURE = "BOT_FAILURE";

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const CREATE_JOB = "CREATE_JOB";
export const RETRIEVE_JOBS = "RETRIEVE_JOBS";
export const UPDATE_JOB = "UPDATE_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const JOB_FAILURE = "JOB_FAILURE";
export const JOB_REQUEST = "JOB_REQUEST";

export const CREATE_FUZZER = "CREATE_FUZZER";
export const RETRIEVE_FUZZERS = "RETRIEVE_FUZZERS";
export const UPDATE_FUZZER = "UPDATE_FUZZER";
export const DELETE_FUZZER = "DELETE_FUZZER";
export const FUZZER_FAILURE = "FUZZER_FAILURE";
export const FUZZER_REQUEST = "FUZZER_REQUEST";

export const CREATE_TASK = "CREATE_FUZZER";
export const TASK_FAILURE = "FUZZER_FAILURE";
export const TASK_REQUEST = "FUZZER_REQUEST";
export const READ_TASKS = "READ_TASKS";
export const READ_ALL_TASKS = "READ_ALL_TASKS";


export const RETRIEVE_TESTCASES = "RETRIE_TESTCASES";
export const TESTCASE_FAILURE = "TESTCASE_FAILURE";
export const TESTCASE_REQUEST = "TESTCASE_REQUEST";


