/* Copyright 2024 IOActive

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

export const CREATE_BOT = "CREATE_BOT";
export const RETRIEVE_BOTS = "RETRIEVE_BOTS";
export const UPDATE_BOT = "UPDATE_BOT";
export const DELETE_BOT = "DELETE_BOT";
export const BOT_REQUEST = "BOT_REQUEST";
export const BOT_SUCCESS = "BOT_SUCCESS";
export const BOT_FAILURE = "BOT_FAILURE";

export const CREATE_BOT_CONFIG = "CREATE_BOT_CONFIG";
export const UPDATE_BOT_CONFIG = "UPDATE_BOT_CONFIG";
export const BOT_CONFIG_REQUEST = "BOT_CONFIG_REQUEST";
export const BOT_CONFIG_SUCCESS = "BOT_CONFIG_SUCCESS";
export const BOT_CONFIG_FAILURE = "BOT_CONFIG_FAILURE";
export const RETRIEVE_BOT_CONFIG = "RETRIEVE_BOT_CONFIG";

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const CREATE_JOB = "CREATE_JOB";
export const RETRIEVE_JOBS = "RETRIEVE_JOBS";
export const UPDATE_JOB = "UPDATE_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const JOB_FAILURE = "JOB_FAILURE";
export const JOB_REQUEST = "JOB_REQUEST";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const RETRIEVE_PROJECTS = "RETRIEVE_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECT_FAILURE = "PROJECT_FAILURE";
export const PROJECT_REQUEST = "PROJECT_REQUEST";

export const CREATE_JOBTEMPLATE = "CREATE_JOBTEMPLATE";
export const RETRIEVE_JOBTEMPLATES = "RETRIEVE_JOBTEMPLATES";
export const UPDATE_JOBTEMPLATE = "UPDATE_JOBTEMPLATE";
export const DELETE_JOBTEMPLATE = "DELETE_JOBTEMPLATE";
export const JOBTEMPLATE_FAILURE = "JOBTEMPLATE_FAILURE";
export const JOBTEMPLATE_REQUEST = "JOBTEMPLATE_REQUEST";

export const CREATE_FUZZER = "CREATE_FUZZER";
export const RETRIEVE_FUZZERS = "RETRIEVE_FUZZERS";
export const UPDATE_FUZZER = "UPDATE_FUZZER";
export const DELETE_FUZZER = "DELETE_FUZZER";
export const FUZZER_FAILURE = "FUZZER_FAILURE";
export const FUZZER_REQUEST = "FUZZER_REQUEST";

export const CREATE_TASK = "CREATE_TASK";
export const TASK_FAILURE = "TASK_FAILURE";
export const TASK_REQUEST = "TASK_REQUEST";
export const READ_TASKS = "READ_TASKS";
export const READ_ALL_TASKS = "READ_ALL_TASKS";


export const RETRIEVE_TESTCASES = "RETRIE_TESTCASES";
export const TESTCASE_FAILURE = "TESTCASE_FAILURE";
export const TESTCASE_REQUEST = "TESTCASE_REQUEST";
export const CREATE_TESTCASE = "CREATE_TESTCASE";


export const RETRIEVE_CRASHES = "RETRIEVE_CRASHES";
export const CRASH_FAILURE = "CRASH_FAILURE";
export const CRASH_REQUEST = "TESTCASE_REQUEST";

export const CREATE_CUSTOM_BINARY = "CREATE_CUSTOM_BINARY";
export const CUSTOM_BINARY_REQUEST = "CUSTOM_BINARY_REQUEST";
export const CUSTOM_BINARY_FAILURE = "CUSTOM_BINARY_FAILURE";

export const CREATE_CORPUS = "CREATE_CORPUS";
export const CORPUS_REQUEST = "CORPUS_REQUEST";
export const CORPUS_FAILURE = "CORPUS_FAILURE";


export const CREATE_BUILD = "CREATE_BUILD";
export const RETRIEVE_BUILDS = "RETRIEVE_BUILDS";
export const UPDATE_BUILD = "UPDATE_BUILD";
export const DELETE_BUILD = "DELETE_BUILD";
export const BUILD_FAILURE = "BUILD_FAILURE";
export const BUILD_REQUEST = "BUILD_REQUEST";


export const RETRIEVE_FUZZER_STATS = "RETRIEVE_FUZZER_STATS";
export const FUZZER_STATS_FAILURE = "FUZZER_STATS_FAILURE";
export const FUZZER_STATS_REQUEST = "FUZZER_STATS_REQUEST";

export const RETRIEVE_FUZZER_TARGETS = "RETRIEVE_FUZZER_TARGETS";
export const FUZZER_TARGET_FAILURE = "FUZZER_TARGET_FAILURE";
export const FUZZER_TARGET_REQUEST = "FUZZER_TARGET_REQUEST";

export const RETRIEVE_CRASH_STATS = "RETRIEVE_CRASH_STATS";
export const CRASH_STATS_REQUEST = "CRASH_STATS_REQUEST";
export const CRASH_STATS_FAILURE = "CRASH_STATS_FAILURE";


export const RETRIEVE_COVERAGE = "RETRIEVE_COVERAGE";
export const COVERAGE_REQUEST = "COVERAGE_REQUEST";
export const COVERAGE_FAILURE = "COVERAGE_FAILURE";
export const DOWNLOAD_ARTIFACTS = "DOWNLOAD_ARTIFACTS";
export const DOWNLOAD_REPORT = "DOWNLOAD_REPORT";



