const Platforms = {
    Windows: "Windows",
    Linux: "Linux",
    Mac: "Mac",
};

export const Fuzzer = (json) => {
    return {
        id: { 
                value: json.id ,
                editable: false,
                header: "UUID",
                type: String,
            },
        timestamp: {
            value: new Date(json.timestamp),
            editable: false,
            header: "Last update time",
            type: Date,
        },
        name: {
            value: json.name,
            editable: true,
            header: "The name of the fuzzer",
            type: String,
        },
        fuzzer_zip: {
            value: json.fuzzer_zip,
            editable: true,
            header: "The fuzzer archive that the user uploaded",
            type: File,
        },
        filename: {
            value: json.filename,
            editable: true,
            header: "The name of the archive that the user uploaded",
            type: String,
        },
        file_size: {
            value: json.file_size,
            editable: false,
            header: "The size of the archive that the user uploaded",
            type: Number,
        },
        blobstore_path: {
            value: json.blobstore_path,
            editable: true,
            header: "The path to the archive in the blobstore",
            type: String,
        },
        executable_path: {
            value: json.executable_path,
            editable: true,
            header: "Fuzzer's main executable path, relative to root",
            type: String,
        },
        revision: {
            value: json.revision,
            editable: true,
            header: "The revision of the fuzzer",
            type: Number,
        },
        timeout: {
            value: json.timeout,
            editable: false,
            header: "Last Testcase timeout",
            type: Date,
        },
        supported_platforms: {
            value: Platforms[json.supported_platforms],
            editable: true,
            header: "The platforms that the fuzzer supports",
            type: Object,
        },
        launcher_script: {
            value: json.launcher_script,
            editable: true,
            header: "Custom script that should be used to launch chrome for this fuzzer",
            type: String,
        },
        result: {
            value: json.result,
            editable: false,
            header: "Result from the last fuzzer run showing the number of testcases generated",
            type: String,
        },
        result_timestamp: {
            value: json.result_timestamp,
            editable: false,
            header: " Last result update timestamp",
            type: Date,
        },
        console_output: {
            value: json.console_output,
            editable: false,
            header: "The console output from the last fuzzer run",
            type: String,
        },
        return_code: {
            value: json.return_code,
            editable: false,
            header: "The return code from the last fuzzer run",
            type: Number,
        },
        sample_testcase: {
            value: json.sample_testcase,
            editable: false,
            header: "Blobstore key for the sample testcase generated by the fuzzer",
            type: String,
        },
        max_testcases: {
            value: json.max_testcases,
            editable: true,
            header: "The maximum number of testcases that the fuzzer should generate",
            type: Number,
        },
        additional_environment_string: {
            value: json.additional_environment_string,
            editable: true,
            header: "Additional environment variables that should be set when running the fuzzer",
            type: String,
        },
        stats_columns: {
            value: json.stats_columns,
            editable: false,
            header: "The columns that should be displayed in the stats table",
            type: Object,
        },
        stats_column_descriptions: {
            value: json.stats_column_descriptions,
            editable: false,
            header: "The descriptions of the columns that should be displayed in the stats table",
            type: Object,
        },
        builtin: {
            value: json.builtin,
            editable: true,
            header: "Whether the fuzzer is built-in or not",
            type: Boolean,
        },
        differential: {
            value: json.differential,
            editable: true,
            header: "Whether the fuzzer is differential or not",
            type: Boolean,
        },
        has_large_testcases: {
            value: json.has_large_testcases,
            editable: true,
            header: "Whether the fuzzer has large testcases or not",
            type: Boolean,
        },
        data_bundle_name: {
            value: json.data_bundle_name,
            editable: true,
            header: "The name of the data bundle that should be used for this fuzzer",
            type: String,
        },
        validated: false,
        submitted: false,
        get_enums: () => {
            return {
                platform: Platforms
            };
        },
    };
};